### ISSUE TITLE
Where can I test this beta out?

### ISSUE THREAD

**Issue by th0mcat** [neatia/Loom#34]
I can't find a link to a TestFlight or an .ipa that I can install myself.  Is there a pic beta for this?

**Comment by pexavc** [comment]
Hey @th0mcat ! Sorry for being late, wildly busy weeks with work and life. I will whip something up soon and send it over. Might just push a new testflight.

**Comment by pexavc** [comment]
@th0mcat pushing a testflight now, https://github.com/neatia/Loom/issues/35 switching servers are broken currently it seems, I will get to it tomorrow. Most likely, logging in will be broken too.

**Comment by pexavc** [comment]
https://testflight.apple.com/join/owwIagmV
